version: '3.8'

services:
  web:
    build: .
    command: gunicorn cinema_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=*
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass

services:
  web:
    build: .
    expose:
      - "8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - HOST=stdev.largent.org

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      - web

volumes:
  pgdata:
  static_data:
  media_data: